### PR TITLE
Simplify portal module

### PR DESCRIPTION
**Pull request by BFergerson**
Simplify portal module using Kotlin MPP instead of multiple modules

### CODE REVIEW

**Comment by BFergerson** [comment]
@chess-equality, with this merged there is no need to run `PortalServer`. From now on just run the mock monitor server and then run the portal via `jsBrowserDevelopmentRun`/`jsBrowserRun` gradle task.

For debugging via IntelliJ you'll need: https://chrome.google.com/webstore/detail/jetbrains-ide-support/hmhgeddbohgjknpmjagkdomcpobmllji

When you are on the portal page instead of "Inspect" you click "Inspect in IDEA" and you're good to go.

**Comment by chess-equality** [comment]
@BFergerson Sorry, how to run the mock monitor server again?

**Comment by BFergerson** [comment]
@chess-equality, the same way as before. The only that has changed is its location.

**Comment by uboznikov** [comment]
@BFergerson Before I'm using the `main` method, but now it's not runnable. Is it via Gradle?

**Comment by BFergerson** [comment]
@BFergerson, it sounds like you are trying to run `PortalServer` instead of `MockMonitorServer`. There is no need for `PortalServer` so I removed the main method. The main method in `MockMonitorServer` still exists.

**Comment by chess-equality** [comment]
@BFergerson 
MockMonitorServer

Branch is up to date:
https://github.com/chess-equality/SourceMarker/tree/feature/issue-251/convert-js-to-kotlin

I did an invalidate cache but it's still the same.

**Comment by BFergerson** [comment]
@chess-equality, try doing this:
Screenshot from 2020-10-13 21-28-36

If that doesn't work try: `./gradlew clean build -x test`

As well as closing and re-opening IntelliJ.

**Comment by chess-equality** [comment]
@BFergerson The reload did it for the `main` method, but I also needed to do the rest because `jsBrowserDevelopmentRun/jsBrowserRun` throws a `Write EPIPE` error if I did not. Thanks.

**Pull request merged**
