### PR TITLE
Bugfix: Issue 1056

### LINKED ISSUE #1056: In dark mode / theme, labels are not showing
add_brkpt_dark-mode-no-labels

### PR DESCRIPTION
**Pull request by chess-equality**
fixes https://github.com/sourceplusplus/sourceplusplus/issues/1056

### CODE REVIEW

**Comment by BFergerson** [comment]
Is this draft or ready for review? Please mark accordingly

**Comment by chess-equality** [comment]
There is an error with `detekt`; I'm checking.

**Comment by chess-equality** [comment]
Ready for review.

**Comment by BFergerson** [comment]
There are visual differences between this and the original version:

Old           |  New
:-------------------------:|:-------------------------:
Screenshot from 2023-07-07 20-53-44 |  Screenshot from 2023-07-07 20-50-34

The old look specifically takes colors from the dark theme to blend in better. There should be no visual differences between the old and new (at least for the dark mode).

**Comment by chess-equality** [comment]
> There are visual differences between this and the original version:
> 
>
> The old look specifically takes colors from the dark theme to blend in better. There should be no visual differences between the old and new (at least for the dark mode).

Fixed in latest commit.

image

**Comment by BFergerson** [comment]
@chess-equality, you're still missing colors.

Check here:
Untitled

You may need to view it using the new UI:
image

**Comment by chess-equality** [comment]
> @chess-equality, you're still missing colors.
> 
> Check here:
> 
> You may need to view it using the new UI:

@BFergerson Is this ok?

image

**Comment by BFergerson** [comment]
@chess-equality, looks right. I'll give it a full review tomorrow.

**Comment by BFergerson** [comment]
@chess-equality, actually wait it looks like you're still using the old UI. I'm more concerned about how it looks in the new UI.

**Comment by chess-equality** [comment]
@BFergerson Here are more screenshots with the new UI.

Part 1 of 2: all dark / all light

image

image

image

image

image

image

**Comment by chess-equality** [comment]
Part 2 of 2: mixed

image

image

image

image

image

image

**Comment by BFergerson** [comment]
@chess-equality, still seeing visible differences.

Old:
image

New:
image

**Comment by chess-equality** [comment]
> @chess-equality, still seeing visible differences.
> 

Fixed in latest commit.

**Comment by BFergerson** [comment]
lgtm

**Pull request merged**
